export function pattern(bpm,rhythm,bars=4){const beat=60/bpm;if(rhythm==='three332')return Array.from({length:bars},(_,i)=>[0,1.5,3].map(t=>(i*4+t)*beat)).flat();if(rhythm==='shapeshift')return Array.from({length:bars*4},(_,i)=>Array.from({length:i%2?5:3},(_,j)=>(i+j/(i%2?5:3))*beat)).flat();if(rhythm==='swingShuffle')return Array.from({length:bars*4},(_,i)=>[0,i%2?2/3:3/5].map(t=>(i+t)*beat)).flat();if(rhythm==='missing16')return Array.from({length:bars*4},(_,i)=>[0,.25,.5,.75].filter((_,j)=>j!==i%4).map(t=>(i+t)*beat)).flat();const ratios={quarter:[0],eighth:[0,.5],sixteenth:[0,.25,.5,.75],triplet:[0,1/3,2/3],offbeat:[.5],shuffle:[0,2/3],shuffleOffbeat:[2/3],five:Array.from({length:5},(_,i)=>i/5),sixteenthOff:[.25,.75],fiveOff:[.8]}[rhythm];return Array.from({length:bars*4},(_,i)=>ratios.map(r=>(i+r)*beat)).flat()}
export function clickEvents(bpm,rhythm,bars=4,guide=false){const beat=60/bpm;return [...Array.from({length:bars*4},(_,i)=>({t:i*beat,accent:i%4===0,guide:false})),...(guide?pattern(bpm,rhythm,bars).filter(t=>Math.abs(t/beat-Math.round(t/beat))>.001).map(t=>({t,accent:false,guide:true})):[])].sort((a,b)=>a.t-b.t)}
export const JUST_MS=10;
export function summarize(notes,extra=0){const errors=notes.filter(n=>Number.isFinite(n.error)).map(n=>n.error),hits=errors.length,total=notes.length,mean=hits?errors.reduce((s,e)=>s+e,0)/hits:0,mae=hits?errors.reduce((s,e)=>s+Math.abs(e),0)/hits:null;const score=total+extra?Math.round(100*errors.reduce((s,e)=>s+Math.max(0,1-Math.max(0,Math.abs(e)-JUST_MS)/90),0)/(total+extra)):0;const spread=hits>=4?Math.sqrt(errors.reduce((s,e)=>s+(e-mean)**2,0)/hits):null;const stability=spread===null?null:Math.round(100*Math.max(0,1-Math.max(0,spread-5)/65));return {score,stability,spread,mean,mae,early:errors.filter(e=>e < -JUST_MS).length,late:errors.filter(e=>e>JUST_MS).length,perfect:errors.filter(e=>Math.abs(e)<=JUST_MS).length,miss:total-hits,extra,hits,total,scoringVersion:3}}
export function upgradeRecord(r){if(!r||!Array.isArray(r.errors))return r;return {...r,...summarize(r.errors.map(error=>({error})),r.extra||0),groove:r.groove||0}}
export function grooveEvents(bpm,rhythm,bars=4,guide=false,groove=0){if(!guide||!groove)return clickEvents(bpm,rhythm,bars,guide);return [...clickEvents(bpm,rhythm,bars,false),...pattern(bpm,rhythm,bars).map(t=>({t:t+groove/1000,accent:false,guide:true}))].sort((a,b)=>a.t-b.t)}

export function handAt(mode,i){return mode==='paradiddleLeft'?['left','right','left','left','right','left','right','right'][i%8]:mode==='paradiddle'?['right','left','right','right','left','right','left','left'][i%8]:mode==='alternateLeft'?(i%2?'right':'left'):mode==='alternate'?(i%2?'left':'right'):mode}

export function recentByMode(records,limit=5){const seen=new Map();return records.filter(r=>{if(!r||typeof r.rhythm!=='string'||typeof r.hand!=='string'||!Number.isFinite(r.score))return false;const key=[!!r.oni,r.rhythm,r.hand,!!r.guide,r.groove||0].join('|'),n=seen.get(key)||0;seen.set(key,n+1);return n<limit})}
